(in-package #:grafico)

(defmethod bfs ((graph graph) start &key (goal nil))
  (let ((queue (make-instance 'deque :items `(,start)))
        (visited '()))
    (loop while (> (length queue) 0)
       do (let ((v (pop-left queue)))
            (when (not (member v visited))
                (setf visited (cons v visited)))
            (if (not (equal goal v))
                (loop for e in (neighbors graph v)
                   do (when (not (member e visited))
                          (progn
                            (setf visited (cons e visited))
                            (append-right queue e)))))))
    (reverse visited)))

(defmethod dfs ((graph graph) start &key (goal nil) (queue nil) (visited nil))
  (let ((queue (when (not queue) (make-instance 'deque :items `(,start))))
        (visited visited))
    (loop while (> (length queue) 0)
       do (let ((v (pop-left queue)))
            (when (not (member v visited))
              (setf visited (cons v visited)))
            (if (not (equal goal v))
                (loop for e in (neighbors graph v)
                   do (when (not (member e visited))
                        (append-left queue e))))
            (dfs graph v :goal goal :queue queue :visited visited)))
    (reverse visited)))
